name: Reusable workflow Tutorial
on: push
jobs:
  Checking Reusable Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Call the re-usable workflow
        uses: ./.github/workflows/reusable.yaml
        with:
          runner_name: {{ runner.os }}
