name: Workflow to Learn actions
on: workflow_dispatch
jobs:
  First_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings Message
        run: echo "Hello Rajat, Welcome to world of Github Actions"
      - name: Print GoodBye Message
        run: echo "See you again ! "
        
