name: Workflow to Learn actions
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code from repository 
        uses: actions/checkout@v3
      - name: MyCurrent Runner directory
        run: pwd
      - name: Printing workspace Variable
        run: |
          echo ${{github.workspace}}
          echo $GITHUB_WORKSPACE
      - name: Install NodeJS 18
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: NodeJs version validate
        run: nodejs -v
