name: Workflow to Learn actions
on: workflow_dispatch
jobs:
  First_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings Message
        run: | 
          echo "Hello Rajat, Welcome to world of Github Actions"
          hostname
      - name: Print Runner Configuration
        run: lscpu

      - name: Print list of packages Installed
        run: sudo apt list --installed
      - name: Print ID of user
        run: id
      - name: Print GoodBye Message
        run: echo "See you again ! "
        
