name: Workflow to Learn action
on: push
env:
  NameofLaptop: "Asus Vivobook"
jobs:
  PrintEV:
    runs-on: ubuntu-latest
    steps:
      - name: Print the environment variables
        run: echo "${{env.NameofLaptop}}"
        
        
