name: Reusable workflow Tutorial
on: push
jobs:
  CheckingReusableWorkflow:
    uses: ./.github/workflows/reusable.yaml
    with:
      variableA: "Rajat"
    secrets:
      abcSecret: ${{ secrets.abc }}
  
  PrintingtheOutcomeofresuableWorkflow:
    needs: CheckingReusableWorkflow
    runs-on: ubuntu-latest
    steps:
      - name: Printing the value
        run: echo ${{ jobs.CheckingReusableWorkflow.outputs.outcome }}
