name: Workflow to Learn action
on: push
env:
  NameofLaptop: "Asus Vivobook"
jobs:
  PrintEV:
    env:
      NameofLaptop: "Asus Vivobook 2"
    runs-on: ubuntu-latest
    steps:
      - name: Print the environment variables by syntax 1
        run: echo "${{env.NameofLaptop}}"
      - name: Print the environment variables by syntax 2
        run: echo $NameofLaptop
      - name: default variables
        run: | 
          echo "Name of Actor $GITHUB_ACTOR"        # this is one of the Default variable. You can not access them via env
          echo "Event name: $GITHUB_EVENT_NAME"
        
        
