name: Workflow to Learn action
on: push
env:
  NameofLaptop: "Asus Vivobook"
jobs:
  PrintEV:
    env:
      NameofLaptop: "Asus Vivobook 2"
    runs-on: ubuntu-latest
    steps:
      - name: Print the environment variables by syntax 1
        run: echo "${{env.NameofLaptop}}"
      - name: Print the environment variables by syntax 2
        run: echo $NameofLaptop
      - name: Actor who kicked of this workflow
        run: echo "Name of Actor $GITHUB_ACTOR"
        
        
