name: Reusable workflow Tutorial
on: push
jobs:
  CheckingReusableWorkflow:
    uses: ./.github/workflows/reusable.yaml
    with:
      variableA: "Rajat"
    secrets:
      abcSecret: {{ secrets.abc }}
