name: Workflow to Learn actions
on: 
  pull_request:
    types: [opened,edited]
  workflow_dispatch:
  push:
    branches:
      - main
      - feature
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code from repository......
        uses: actions/checkout@v3
      - name: MyCurrent Runner directory
        run: pwd
      - name: Printing workspace Variable
        run: |
          echo ${{github.workspace}}
          echo $GITHUB_WORKSPACE
      - name: Install NodeJS 18
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - name: Installing dependencies
        run: npm c

      - name: NodeJs version validate
        run: node -v
        
  deploy:
    runs-on: ubuntu-latest
    needs: test              #we can use [jobname1,jobname2....so on]
    steps:
      - name: Download the code from repository 
        uses: actions/checkout@v3
      - name: MyCurrent Runner directory
        run: pwd
      - name: Printing workspace Variable
        run: |
          echo ${{github.workspace}}
          echo $GITHUB_WORKSPACE
      - name: Install NodeJS 18
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - name: Installing dependencies
        run: npm ci

      - name: NodeJs version validate
        run: node -v
      - name: Build
        run: npm run build
        
