name: This is the reusable workflow
on: 
  workflow_call:
    inputs:
      variableA:
        type: string
        required: false
        
jobs: 
  reusableJob:
    runs-on: ubuntu-latest
    steps:
      name: Print that variable
      run: echo ${{inputs.variableA}}
      
    
